version: '3.7'
services:
  bandla-app:
    build:
      context: .
    container_name: bandla
    image: nazarovv2/bandla:latest
    ports:
      - "80:80"
    environment:
      - SECURITY_ACCESS_TOKEN_SECRET_KEY=${SECURITY_ACCESS_TOKEN_SECRET_KEY}
      - SECURITY_REFRESH_TOKEN_SECRET_KEY=${SECURITY_REFRESH_TOKEN_SECRET_KEY}
      - SECURITY_TEMPORARY_TOKEN_SECRET_KEY=${SECURITY_TEMPORARY_TOKEN_SECRET_KEY}
      - SECURITY_ACCESS_TOKEN_LIVE=${SECURITY_ACCESS_TOKEN_LIVE}
      - SECURITY_REFRESH_TOKEN_LIVE=${SECURITY_REFRESH_TOKEN_LIVE}
      - SECURITY_TEMPORARY_TOKEN_LIVE=${SECURITY_TEMPORARY_TOKEN_LIVE}
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - net
networks:
  net:
    driver: "bridge"