name: Only tests

on:
  push:
    branches-ignore:
      - production
      - master
      - debug

jobs:
  run-all-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 'Create env file'
        run: |
          touch .env
          echo BOT_NAME=${{ secrets.BOT_NAME}} >> .env
          echo BOT_TOKEN=${{ secrets.BOT_TOKEN}} >> .env
          echo AWS_CREDENTIALS_ACCESS_KEY=${secrets.AWS_CREDENTIALS_ACCESS_KEY} >> .env
          echo AWS_CREDENTIALS_SECRET_KEY=${{ secrets.AWS_CREDENTIALS_SECRET_KEY}} >> .env
          echo AWS_S3_BUCKET_REGION_STATIC=${{ secrets.AWS_S3_BUCKET_REGION_STATIC}} >> .env
          echo AWS_S3_BUCKET_STACK_AUTO=${{ secrets.AWS_S3_BUCKET_STACK_AUTO}} >> .env
          echo AWS_S3_BUCKET_NAME=${{ secrets.AWS_S3_BUCKET_NAME}} >> .env
          cat .env

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Setup Maven
        uses: stCarolas/setup-maven@v4.4
        with:
          maven-version: 3.8.6

      - name: All the Tests and Coverage Checks
        run: mvn clean install